


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."approve_project_force"("p_request_id" "uuid", "p_client_type" "text") RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_target_status text;
  v_final_type text;
BEGIN
  -- Default to Direct if null
  v_final_type := COALESCE(p_client_type, 'Direct');

  -- Determine strict status based on type
  IF v_final_type = 'Roster' THEN
    v_target_status := 'f15_production';
  ELSE
    v_target_status := 'approved';
  END IF;

  -- 1. Update the Main Request
  UPDATE public."2_booking_requests"
  SET status = v_target_status,
      client_type = v_final_type
  WHERE id = p_request_id;

  -- 2. ROUTING LOGIC (The "Nuclear" Option)
  IF v_target_status = 'f15_production' THEN
    -- Force into F15
    INSERT INTO public."4_first_15" (request_id)
    SELECT p_request_id
    WHERE NOT EXISTS (SELECT 1 FROM public."4_first_15" WHERE request_id = p_request_id);

    -- Force DELETE from Onboarding (Fixes the "Shows in Onboarding" bug)
    DELETE FROM public."3_onboarding" WHERE request_id = p_request_id;

  ELSE
    -- Force into Onboarding
    INSERT INTO public."3_onboarding" (request_id)
    SELECT p_request_id
    WHERE NOT EXISTS (SELECT 1 FROM public."3_onboarding" WHERE request_id = p_request_id);

    -- Force DELETE from F15 (Clean up)
    DELETE FROM public."4_first_15" WHERE request_id = p_request_id;
  END IF;

END;
$$;


ALTER FUNCTION "public"."approve_project_force"("p_request_id" "uuid", "p_client_type" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_public_schedule"() RETURNS TABLE("start_date" "date", "end_date" "date", "status" "text")
    LANGUAGE "sql" SECURITY DEFINER
    AS $$
  select start_date, end_date, status
  from bookings
  where end_date >= CURRENT_DATE -- Only show future/current bookings
$$;


ALTER FUNCTION "public"."get_public_schedule"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_view"("page_slug" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  UPDATE public.posts
  SET views = views + 1
  WHERE slug = page_slug;
END;
$$;


ALTER FUNCTION "public"."increment_view"("page_slug" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."10_session_logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "project_id" "uuid",
    "date" "date" DEFAULT CURRENT_DATE,
    "activity" "text",
    "duration_hrs" numeric(10,2) DEFAULT 0,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."10_session_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."12_voiceover_notes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "category" "text" NOT NULL,
    "title" "text",
    "content" "jsonb"
);


ALTER TABLE "public"."12_voiceover_notes" OWNER TO "postgres";


ALTER TABLE "public"."12_voiceover_notes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."11_voiceover_notes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."11_voiceover_tracker" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "project_title" "text" NOT NULL,
    "client_name" "text",
    "platform" "text" DEFAULT 'Direct'::"text",
    "rate" "text",
    "status" "text" DEFAULT 'inbox'::"text",
    "due_date" timestamp with time zone,
    "notes" "text",
    "source_email" "text",
    "role" "text",
    "specs" "text",
    "direction" "text",
    "audition_link" "text",
    "file_link" "text",
    "submitted_timezone" "text",
    "timezone" "text" DEFAULT 'America/Los_Angeles'::"text",
    "submitted_at" timestamp with time zone
);


ALTER TABLE "public"."11_voiceover_tracker" OWNER TO "postgres";


ALTER TABLE "public"."11_voiceover_tracker" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."11_voiceover_tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."1_responsive_leads" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "full_name" "text",
    "company_name" "text",
    "email" "text",
    "lead_type" "text",
    "lead_source" "text",
    "platform" "text",
    "last_reply" "text",
    "vibes" "text",
    "next_action" "text",
    "days_dormant" integer DEFAULT 0,
    "status" "text" DEFAULT 'active'::"text",
    "last_reply_date" "date" DEFAULT CURRENT_DATE
);


ALTER TABLE "public"."1_responsive_leads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."2_booking_requests" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "client_name" "text",
    "email" "text",
    "client_type" "text",
    "is_returning" boolean DEFAULT false,
    "book_title" "text",
    "word_count" integer,
    "narration_style" "text",
    "genre" "text",
    "notes" "text",
    "start_date" "date",
    "end_date" "date",
    "days_needed" integer,
    "discount_applied" "text",
    "status" "text" DEFAULT 'pending'::"text",
    "cover_image_url" "text",
    "ref_number" "text",
    "email_secondary" "text",
    "email_tertiary" "text",
    "email_thread_link" "text"
);


ALTER TABLE "public"."2_booking_requests" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."3_onboarding_first_15" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "request_id" "uuid",
    "added_to_contacts" boolean DEFAULT false,
    "backend_folder" boolean DEFAULT false,
    "docs_customized" boolean DEFAULT false,
    "production_folder" boolean DEFAULT false,
    "contract_sent" boolean DEFAULT false,
    "esig_sent" boolean DEFAULT false,
    "contract_signed_date" "date",
    "contract_signed" boolean DEFAULT false,
    "deposit_sent" boolean DEFAULT false,
    "deposit_paid_date" "date",
    "deposit_paid" boolean DEFAULT false,
    "email_receipt_sent" boolean DEFAULT false,
    "breakdown_received_date" "date",
    "breakdown_received" boolean DEFAULT false,
    "manuscript_received" boolean DEFAULT false,
    "f15_due_internal" "date",
    "f15_sent_date" "date",
    "f15_client_due_date" "date",
    "f15_feedback_received_date" "date",
    "f15_revision_req" boolean DEFAULT false,
    "f15_r2_due_internal" "date",
    "f15_r2_sent_date" "date",
    "f15_r2_client_due_date" "date",
    "f15_approved" boolean DEFAULT false,
    "strike_count" integer DEFAULT 0,
    "last_nudge_date" "date",
    "current_status" "text" DEFAULT 'Onboarding'::"text",
    "refund_status" "text" DEFAULT 'None'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "step_dates" "jsonb" DEFAULT '{}'::"jsonb",
    "refund_percentage" integer DEFAULT 0,
    "refund_date" "date"
);


ALTER TABLE "public"."3_onboarding_first_15" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."4_production" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "request_id" "uuid",
    "status" "text" DEFAULT 'pre_production'::"text",
    "recording_start_date" "date",
    "recording_due_date" "date",
    "files_sent_date" "date",
    "crx_status" "text" DEFAULT 'none'::"text",
    "crx_due_date" "date",
    "characters" "jsonb" DEFAULT '[]'::"jsonb",
    "crx_batches" "jsonb" DEFAULT '[]'::"jsonb",
    "checklist" "jsonb" DEFAULT '[]'::"jsonb",
    "strikes" integer DEFAULT 0,
    "internal_notes" "text" DEFAULT ''::"text",
    "pozotron_rate" numeric(10,2) DEFAULT 14.00,
    "pfh_rate" numeric DEFAULT 250,
    "other_expenses" "jsonb" DEFAULT '[]'::"jsonb",
    "active_timer_start" timestamp with time zone,
    "active_timer_elapsed" numeric DEFAULT 0,
    "active_timer_activity" "text" DEFAULT 'Recording'::"text"
);


ALTER TABLE "public"."4_production" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."5_auditions" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "client_name" "text",
    "script_text" "text",
    "audio_file_url" "text",
    "status" "text" DEFAULT 'open'::"text",
    "book_title" "text",
    "roster_producer" "text",
    "end_date" "date",
    "production_status" "text" DEFAULT 'auditioning'::"text",
    "material_url" "text"
);


ALTER TABLE "public"."5_auditions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."6_archive" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "original_data" "jsonb",
    "archived_at" timestamp with time zone DEFAULT "now"(),
    "reason" "text"
);


ALTER TABLE "public"."6_archive" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."7_bookouts" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "reason" "text",
    "type" "text"
);


ALTER TABLE "public"."7_bookouts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."8_do_not_contact" (
    "id" bigint NOT NULL,
    "full_name" "text",
    "indie_or_company" "text",
    "email" "text",
    "lead_type" "text",
    "reason" "text",
    "date_last_contacted" "date"
);


ALTER TABLE "public"."8_do_not_contact" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."9_invoices" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "project_id" "uuid",
    "total_amount" numeric DEFAULT 0,
    "deposit_amount" numeric DEFAULT 0,
    "final_amount" numeric DEFAULT 0,
    "currency" "text" DEFAULT 'USD'::"text",
    "deposit_status" "text" DEFAULT 'pending'::"text",
    "deposit_date_paid" "date",
    "final_status" "text" DEFAULT 'pending'::"text",
    "final_date_paid" "date",
    "invoice_pdf_link" "text",
    "tracker_sheet_link" "text",
    "notes" "text",
    "reference_number" "text",
    "pfh_count" numeric DEFAULT 0,
    "pfh_rate" numeric DEFAULT 0,
    "invoiced_date" "date",
    "due_date" "date",
    "reminders_sent" integer DEFAULT 0,
    "sag_ph_percent" numeric DEFAULT 0,
    "convenience_fee" numeric DEFAULT 0,
    "ledger_tab" "text" DEFAULT 'open'::"text",
    "contract_link" "text",
    "custom_note" "text",
    "payment_link" "text",
    "pozotron_rate" numeric(10,2) DEFAULT 14.00,
    "other_expenses" numeric(10,2) DEFAULT 0,
    "est_tax_rate" numeric(10,2) DEFAULT 25.00,
    "logo_url" "text",
    "line_items" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."9_invoices" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."task_master_items" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "type" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    "title" "text",
    "content" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb",
    "tags" "text"[],
    "parent_id" "uuid",
    "recurrence_interval" "text",
    "due_date" timestamp with time zone,
    "recurrence" "text",
    "position" double precision DEFAULT 0,
    CONSTRAINT "task_master_items_recurrence_check" CHECK (("recurrence" = ANY (ARRAY['daily'::"text", 'weekly'::"text", 'monthly'::"text", 'quarterly'::"text", 'yearly'::"text", 'one_off'::"text", NULL::"text"]))),
    CONSTRAINT "task_master_items_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'completed'::"text", 'archived'::"text", 'in_progress'::"text"]))),
    CONSTRAINT "task_master_items_type_check" CHECK (("type" = ANY (ARRAY['task'::"text", 'code_snippet'::"text", 'social_bookmark'::"text", 'resource'::"text", 'level_up'::"text", 'ledger'::"text", 'file_structure'::"text", 'idea_board'::"text"])))
);


ALTER TABLE "public"."task_master_items" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."distinct_tags" AS
 SELECT DISTINCT "unnest"("tags") AS "tag_name"
   FROM "public"."task_master_items";


ALTER VIEW "public"."distinct_tags" OWNER TO "postgres";


ALTER TABLE "public"."8_do_not_contact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."do_not_contact_leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "date" "text" NOT NULL,
    "tag" "text",
    "image" "text",
    "content" "text",
    "image_caption" "text",
    "views" integer DEFAULT 0,
    "image_2" "text",
    "image_3" "text",
    "image_4" "text",
    "image_5" "text",
    "published" boolean DEFAULT false,
    "author" "text",
    "image_6" "text",
    "music_embed" "text",
    "blogcast_url" "text"
);


ALTER TABLE "public"."posts" OWNER TO "postgres";


ALTER TABLE ONLY "public"."10_session_logs"
    ADD CONSTRAINT "10_session_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."12_voiceover_notes"
    ADD CONSTRAINT "11_voiceover_notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."11_voiceover_tracker"
    ADD CONSTRAINT "11_voiceover_tracker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."1_responsive_leads"
    ADD CONSTRAINT "1_responsive_leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."2_booking_requests"
    ADD CONSTRAINT "2_booking_requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."3_onboarding_first_15"
    ADD CONSTRAINT "3_onboarding_f15_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."4_production"
    ADD CONSTRAINT "6_production_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."5_auditions"
    ADD CONSTRAINT "7_auditions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."6_archive"
    ADD CONSTRAINT "8_archive_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."7_bookouts"
    ADD CONSTRAINT "9_bookouts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."9_invoices"
    ADD CONSTRAINT "9_invoices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."8_do_not_contact"
    ADD CONSTRAINT "do_not_contact_leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."task_master_items"
    ADD CONSTRAINT "task_master_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."9_invoices"
    ADD CONSTRAINT "unique_project_invoice" UNIQUE ("project_id");



ALTER TABLE ONLY "public"."10_session_logs"
    ADD CONSTRAINT "10_session_logs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."2_booking_requests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."3_onboarding_first_15"
    ADD CONSTRAINT "3_onboarding_f15_request_fkey" FOREIGN KEY ("request_id") REFERENCES "public"."2_booking_requests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."4_production"
    ADD CONSTRAINT "4_production_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "public"."2_booking_requests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."9_invoices"
    ADD CONSTRAINT "9_invoices_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."2_booking_requests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."task_master_items"
    ADD CONSTRAINT "task_master_items_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."task_master_items"("id");



ALTER TABLE ONLY "public"."task_master_items"
    ADD CONSTRAINT "task_master_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE "public"."10_session_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."11_voiceover_tracker" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."12_voiceover_notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."1_responsive_leads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."2_booking_requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."3_onboarding_first_15" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."4_production" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."5_auditions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."6_archive" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."7_bookouts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."8_do_not_contact" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."9_invoices" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Admin All Invoices" ON "public"."9_invoices" TO "authenticated" USING (true);



CREATE POLICY "Admin Full Access" ON "public"."10_session_logs" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."11_voiceover_tracker" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."1_responsive_leads" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."2_booking_requests" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."3_onboarding_first_15" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."4_production" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."5_auditions" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."6_archive" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."7_bookouts" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."8_do_not_contact" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."9_invoices" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Full Access" ON "public"."posts" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Only Access" ON "public"."9_invoices" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admin Write Blockouts" ON "public"."7_bookouts" FOR INSERT TO "authenticated", "service_role" WITH CHECK (true);



CREATE POLICY "Allow Delete" ON "public"."7_bookouts" FOR DELETE TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "Allow access to authenticated users" ON "public"."12_voiceover_notes" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable all access for authenticated users" ON "public"."11_voiceover_tracker" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Public Insert Access" ON "public"."2_booking_requests" FOR INSERT TO "authenticated", "anon", "service_role" WITH CHECK (true);



CREATE POLICY "Public Read" ON "public"."posts" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Public Read Access" ON "public"."2_booking_requests" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "Public Read Blockouts" ON "public"."7_bookouts" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "Public View" ON "public"."posts" FOR SELECT USING (true);



CREATE POLICY "owner_full_access" ON "public"."task_master_items" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."task_master_items" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."4_production";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."approve_project_force"("p_request_id" "uuid", "p_client_type" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."approve_project_force"("p_request_id" "uuid", "p_client_type" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."approve_project_force"("p_request_id" "uuid", "p_client_type" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_public_schedule"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_public_schedule"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_public_schedule"() TO "service_role";



GRANT ALL ON FUNCTION "public"."increment_view"("page_slug" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."increment_view"("page_slug" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_view"("page_slug" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."10_session_logs" TO "anon";
GRANT ALL ON TABLE "public"."10_session_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."10_session_logs" TO "service_role";



GRANT ALL ON TABLE "public"."12_voiceover_notes" TO "anon";
GRANT ALL ON TABLE "public"."12_voiceover_notes" TO "authenticated";
GRANT ALL ON TABLE "public"."12_voiceover_notes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."11_voiceover_notes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."11_voiceover_notes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."11_voiceover_notes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."11_voiceover_tracker" TO "anon";
GRANT ALL ON TABLE "public"."11_voiceover_tracker" TO "authenticated";
GRANT ALL ON TABLE "public"."11_voiceover_tracker" TO "service_role";



GRANT ALL ON SEQUENCE "public"."11_voiceover_tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."11_voiceover_tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."11_voiceover_tracker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."1_responsive_leads" TO "anon";
GRANT ALL ON TABLE "public"."1_responsive_leads" TO "authenticated";
GRANT ALL ON TABLE "public"."1_responsive_leads" TO "service_role";



GRANT ALL ON TABLE "public"."2_booking_requests" TO "anon";
GRANT ALL ON TABLE "public"."2_booking_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."2_booking_requests" TO "service_role";



GRANT ALL ON TABLE "public"."3_onboarding_first_15" TO "anon";
GRANT ALL ON TABLE "public"."3_onboarding_first_15" TO "authenticated";
GRANT ALL ON TABLE "public"."3_onboarding_first_15" TO "service_role";



GRANT ALL ON TABLE "public"."4_production" TO "anon";
GRANT ALL ON TABLE "public"."4_production" TO "authenticated";
GRANT ALL ON TABLE "public"."4_production" TO "service_role";



GRANT ALL ON TABLE "public"."5_auditions" TO "anon";
GRANT ALL ON TABLE "public"."5_auditions" TO "authenticated";
GRANT ALL ON TABLE "public"."5_auditions" TO "service_role";



GRANT ALL ON TABLE "public"."6_archive" TO "anon";
GRANT ALL ON TABLE "public"."6_archive" TO "authenticated";
GRANT ALL ON TABLE "public"."6_archive" TO "service_role";



GRANT ALL ON TABLE "public"."7_bookouts" TO "anon";
GRANT ALL ON TABLE "public"."7_bookouts" TO "authenticated";
GRANT ALL ON TABLE "public"."7_bookouts" TO "service_role";



GRANT ALL ON TABLE "public"."8_do_not_contact" TO "anon";
GRANT ALL ON TABLE "public"."8_do_not_contact" TO "authenticated";
GRANT ALL ON TABLE "public"."8_do_not_contact" TO "service_role";



GRANT ALL ON TABLE "public"."9_invoices" TO "anon";
GRANT ALL ON TABLE "public"."9_invoices" TO "authenticated";
GRANT ALL ON TABLE "public"."9_invoices" TO "service_role";



GRANT ALL ON TABLE "public"."task_master_items" TO "anon";
GRANT ALL ON TABLE "public"."task_master_items" TO "authenticated";
GRANT ALL ON TABLE "public"."task_master_items" TO "service_role";



GRANT ALL ON TABLE "public"."distinct_tags" TO "anon";
GRANT ALL ON TABLE "public"."distinct_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."distinct_tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."do_not_contact_leads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."do_not_contact_leads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."do_not_contact_leads_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."posts" TO "anon";
GRANT ALL ON TABLE "public"."posts" TO "authenticated";
GRANT ALL ON TABLE "public"."posts" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "Public Insert Access" on "public"."2_booking_requests";

drop policy "Public Read Access" on "public"."2_booking_requests";

drop policy "Allow Delete" on "public"."7_bookouts";

drop policy "Public Read Blockouts" on "public"."7_bookouts";


  create policy "Public Insert Access"
  on "public"."2_booking_requests"
  as permissive
  for insert
  to anon, authenticated, service_role
with check (true);



  create policy "Public Read Access"
  on "public"."2_booking_requests"
  as permissive
  for select
  to anon, authenticated, service_role
using (true);



  create policy "Allow Delete"
  on "public"."7_bookouts"
  as permissive
  for delete
  to anon, authenticated, service_role
using (true);



  create policy "Public Read Blockouts"
  on "public"."7_bookouts"
  as permissive
  for select
  to anon, authenticated, service_role
using (true);



  create policy "Admin All Admin Bucket"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using ((bucket_id = 'admin'::text))
with check ((bucket_id = 'admin'::text));



  create policy "Admin Update Delete"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using ((bucket_id = 'blog-images'::text));



  create policy "Auth All Images"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using ((bucket_id = 'blog-images'::text))
with check ((bucket_id = 'blog-images'::text));



  create policy "Auth Manage Images"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using ((bucket_id = 'blog-images'::text))
with check ((bucket_id = 'blog-images'::text));



  create policy "Public Read Admin Bucket"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'admin'::text));



  create policy "Public Select Images"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'blog-images'::text));



  create policy "Public allowed to see images bjsgsj_0"
  on "storage"."objects"
  as permissive
  for select
  to anon
using ((bucket_id = 'blog-images'::text));



